### ISSUE TITLE
How can I play this game macOS?

### ISSUE THREAD

**Issue by Masynchin** [basile-henry/infinisweep#9]
During installation with `stack` I have this error:

~~~plain
No setup information found for ghc-8.4.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'macosx-aarch64'.
Supported versions: ghc-8.10.5, ghc-8.10.6, ghc-8.10.7, ghc-9.0.2, ghc-9.2.1, ghc-9.2.2, ghc-9.2.3
No setup information found for ghc-8.4.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'macosx-aarch64'.
Supported versions: ghc-8.10.5, ghc-8.10.6, ghc-8.10.7, ghc-9.0.2, ghc-9.2.1, ghc-9.2.2, ghc-9.2.3
~~~

Is it any way for me to run this game?

**Comment by basile-henry** [comment]
I don't have a macOS machine on hand to test with, but this error message seems to suggest that if I upgrade to a more recent version of GHC and package set (from stackage), then maybe it'll be supported on `macosx-aarch64`.
I will upgrade the dependencies, so you can try again from macOS, but I can't promise it'll work.

Another possibility is for you to use the `cabal` workflow, which you can install along with GHC using [`ghcup`](https://www.haskell.org/ghcup/). Or yet another possibility would be to use the `nix` workflow.

**Comment by Masynchin** [comment]
Thanks for updating supported version! Now the only issue is with ncurses, which doesn't want to compile. I will reply when successfully fix this.

**Comment by basile-henry** [comment]
Are you compiling `ncurses` from scratch? I would expect `brew install ncurses` to be enough.
Post error messages if you have any 😊

Otherwise the `nix` workflow doesn't require you to install `ncurses` separately as it uses the one provided by `nixpkgs`.

**Comment by Masynchin** [comment]
> Are you compiling `ncurses` from scratch? I would expect `brew install ncurses` to be enough.

No, I already have installed ncurses (of 6.3 version, is 5 needed?). I mean `stack build` compilation, it raises error.

> Post error messages if you have any.

`stack setup` works correct, but `stack build` raises this:

~~~plain
ncurses    > configure
ncurses    > Warning: ncurses.cabal:85:21: version operators used. To use version operators
ncurses    > the package needs to specify at least 'cabal-version: >= 1.8'.
ncurses    > Configuring ncurses-0.2.16...
ncurses    > build
ncurses    > Preprocessing library for ncurses-0.2.16..
ncurses    > c2hs: C header contains errors:
ncurses    >
ncurses    > /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/time.h:198: (column 23) [ERROR]  >>> Syntax error !
ncurses    >   The symbol `(' does not fit here.
ncurses    >
Progress 1/2

--  While building package ncurses-0.2.16 (scroll up to its section to see the error) using:
      /Users/maxsmirnov/.stack/setup-exe-cache/aarch64-osx/Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2 --builddir=.stack-work/dist/aarch64-osx/Cabal-3.4.1.0 build --ghc-options " -fdiagnostics-color=always"
~~~

Before this I had [ffi error](https://gitlab.haskell.org/ghc/ghc/-/issues/20592), but I fix this as suggested in discussion.

Cabal workflow raises exactly this error. I didn't try Nix workflow, because I don't know much about this tool and too afraid now to install it 😁.

**Comment by basile-henry** [comment]
> of 6.3 version, is 5 needed?

I think either should work

I have managed to replicate the error you are seeing in CI #11, but I am not sure how to fix it, and it's quite hard for me to debug using only CI :sweat_smile: 
This PR #11 does confirm that the nix workflow does build properly even on macOS though :grin:

**Comment by basile-henry** [comment]
I have removed the dependency on the old ncurses bindings for Haskell and used the `vty` package instead in #12. It still uses ncurses under the hood but with better bindings as far as I can tell. CI with macOS (x86) does now pass, so maybe it now works for you as well :crossed_fingers:

**Comment by Masynchin** [comment]
@basile-henry thanks!!! Now I can build this beautiful game and play it. Huge thanks for resolving my Issue.
